"""Turns the address registry into the agent's addresses.

    python tools/addr.py [path\to\mappings.json]

Every game address the agent uses passes through here. A hand-written address in
agent or zygote code is a bug: a wrong RVA gives a hook that silently never
fires, which costs a debugging session to notice.
"""
import json
import sys

import paths

OUT_JS = paths.ROOT / "agent" / "src" / "gen" / "addr.js"
# What the game's own code looked like at each hooked site when the addresses
# were found. Written by tools/hooksafe.py --signatures, committed because
# neither CI nor a mod author has the binary, and carried into the agent so it
# can tell at attach whether it is looking at that build or another one.
SIG_JSON = paths.ROOT / "agent" / "signatures.json"


def main(argv):
    config = paths.registry(argv)

    out = ["// Generated by tools/addr.py from the mappings repository.",
           "// Do not edit. Add the address to mappings.txt instead.",
           "",
           "var RVA = {"]
    out += [f"    {name}: {value}," for name, value in config["rva"].items()]
    out += ["};", "", "var VA = {"]
    out += [f"    {name}: {value}," for name, value in config["va"].items()]
    out += ["};", ""]

    build = signatures()
    if build:
        out += ["var BUILD = {",
                f'    exe: "{build["exe"]}",',
                f'    version: "{build["version"]}",',
                "    sig: {"]
        out += [f'        {name}: "{sig}",' for name, sig in build["sig"].items()]
        out += ["    },", "};", ""]

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text("\n".join(out), encoding="utf-8")
    print(f"agent/src/gen/addr.js: {len(config['rva'])} RVAs, "
          f"{len(config['va'])} globals, "
          f"{len(build['sig']) if build else 0} site signatures")
    return 0


def signatures():
    """The build fingerprint, or nothing when the file is not there.

    Missing is survivable on purpose: an agent bundled without it simply skips
    the check rather than refusing to load.
    """
    if not SIG_JSON.is_file():
        return None
    return json.loads(SIG_JSON.read_text(encoding="utf-8"))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
