"""Refuses hook sites a trampoline would corrupt.

Frida replaces the instruction at a hook with a five-byte jump.  If the
instruction is shorter, the jump spills onto the next one -- and if any branch
in the binary lands in that spill, the game jumps into the middle of the
trampoline and dies.

That is not theoretical: the skill write at +0x1827DA is four bytes long and two
jumps target the instruction right after it, which crashed the game while
loading any character with an empty skill slot.  Three game restarts to find by
hand, one second to find here.

It also owns the agent's build fingerprint.  The bytes it reads at every hooked
site are exactly what the agent has to find there for its addresses to still
mean anything, so `--signatures` writes them to `agent/signatures.json` and a
plain run reports whether the binary in front of it still matches that file.

    python tools/hooksafe.py [path to the game.exe, or to the Sacred Gold folder]
    python tools/hooksafe.py --signatures [path]   rewrite agent/signatures.json
"""
import bisect
import json
import pathlib
import sys

import pefile
from capstone import CS_ARCH_X86, CS_MODE_32, Cs
from capstone.x86 import X86_OP_IMM

import game
import paths

ROOT = paths.ROOT
IMAGE_BASE = 0x00400000
TRAMPOLINE = 5   # bytes Frida needs for its jump

# What the agent compares against at attach.  Committed, because neither CI nor
# a mod author has the game: the file is regenerated here, from a real binary.
SIG_FILE = ROOT / "agent" / "signatures.json"
# Long enough that two builds cannot agree at twenty sites by accident, short
# enough to stay well inside .text at every one of them.
SIG_BYTES = 8

# The folder, not the file: which executable is in there is game.find's
# business, and a stock install holds a different one.
DEFAULT_DIR = pathlib.Path(r"D:\SteamLibrary\steamapps\common\Sacred Gold")


def text_section(exe):
    pe = pefile.PE(str(exe), fast_load=True)
    raw = exe.read_bytes()
    section = next(s for s in pe.sections
                   if s.Name.rstrip(b"\x00") == b".text")
    start = IMAGE_BASE + section.VirtualAddress
    body = raw[section.PointerToRawData:
               section.PointerToRawData + section.SizeOfRawData]
    return start, body


def file_version(exe):
    """The four numbers in VS_FIXEDFILEINFO, not the version *string*.

    The strings lie by omission in exactly this family of binaries: pureHD.exe
    spells its FileVersion "2.28" and the stock Sacred.exe spells it "2.0",
    while the fixed block says 2.0.2.118 and 2.0.2.28. The numbers are the half
    that tells the two apart.
    """
    pe = pefile.PE(str(exe), fast_load=True)
    pe.parse_data_directories(
        directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_RESOURCE"]])
    info = getattr(pe, "VS_FIXEDFILEINFO", None)
    if not info:
        return "unknown"
    ms, ls = info[0].FileVersionMS, info[0].FileVersionLS
    return f"{ms >> 16}.{ms & 0xFFFF}.{ls >> 16}.{ls & 0xFFFF}"


def signatures(sites, start, body):
    """The first SIG_BYTES bytes at every hooked site, as hex.

    The image has its relocations stripped and no /DYNAMICBASE, so it always
    loads at 0x00400000 and these bytes are byte-for-byte what the agent reads
    out of the running process.
    """
    found = {}
    for site, name in sites.items():
        chunk = body[site - start:site - start + SIG_BYTES]
        if len(chunk) == SIG_BYTES:
            found[name] = chunk.hex()
    return found


def write_signatures(found, exe):
    SIG_FILE.write_text(json.dumps({
        "_": "Generated by tools/hooksafe.py --signatures from the game binary. "
             "Read into agent/src/gen/addr.js by tools/addr.py, and compared "
             "against the running process by 10-core.js at attach.",
        "exe": exe.name,
        "version": file_version(exe),
        "sig": dict(sorted(found.items())),
    }, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"agent/signatures.json: {len(found)} sites of "
          f"{exe.name} {file_version(exe)}")


def compare_signatures(found, exe):
    """Whether the binary in front of us is still the one the agent expects."""
    if not SIG_FILE.is_file():
        return ("agent/signatures.json is missing -- "
                "run tools/hooksafe.py --signatures against the HD wrapper")
    expected = json.loads(SIG_FILE.read_text(encoding="utf-8"))
    known = expected["sig"]
    differ = sorted(name for name, sig in known.items() if found.get(name) != sig)
    build = f"{expected['exe']} {expected['version']}"
    if not differ:
        return f"signatures: all {len(known)} sites match {build}"
    shown = ", ".join(differ[:4]) + (", ..." if len(differ) > 4 else "")
    return (f"signatures: {len(differ)} of {len(known)} sites differ from "
            f"{build} ({shown}) -- {exe.name} {file_version(exe)} is a "
            f"different build, and the agent will say so at attach")


def main():
    argv = list(sys.argv[1:])
    rewrite = "--signatures" in argv
    if rewrite:
        argv.remove("--signatures")
    where = pathlib.Path(argv[0]) if argv else DEFAULT_DIR
    # An argument may name the folder or the executable itself; both are what
    # somebody has to hand.
    exe = where if where.is_file() else game.find(where)
    if exe is None:
        print(f"skipped: no game in {where} "
              f"({game.names()}) -- pass the path to check")
        return 0

    config = paths.registry()
    sites = {IMAGE_BASE + int(config["rva"][name], 16): name
             for name in config["hooked"]}

    start, body = text_section(exe)
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    md.detail = True
    # Without this, linear disassembly stops dead at the first byte it cannot
    # decode -- and .text is full of data.  A silent early stop makes this check
    # pass everything, which is worse than not having it.
    md.skipdata = True

    # How many bytes each hook really costs: Frida relocates WHOLE instructions,
    # so it takes instructions from the site until it has at least five bytes.
    # A fixed five- or six-byte window under-reports -- `cmp` plus a rel32 `je`
    # is eight, and the two bytes past a naive window are exactly where a branch
    # was landing.
    patched = {}
    for site in sites:
        offset = site - start
        covered = 0
        for insn in md.disasm(body[offset:offset + 32], site):
            covered += insn.size
            if covered >= TRAMPOLINE:
                break
        patched[site] = site + max(covered, TRAMPOLINE)

    # A branch is fatal when it lands strictly inside a patch area.  Landing on
    # the first byte is how every normal call reaches a hooked function.
    fatal = []
    risky = []
    # Anything the binary `call`s is a function entry.  Frida is at its safest
    # there -- a real return address, a prologue to relocate -- so the hazards
    # below that are about relocating mid-function code do not apply.
    entries = set()
    for insn in md.disasm(body, start):
        if insn.id == 0 or not insn.operands:
            continue
        if not (insn.mnemonic.startswith("j")
                or insn.mnemonic in ("call", "loop")):
            continue
        if insn.operands[0].type != X86_OP_IMM:
            continue
        target = insn.operands[0].imm
        if insn.mnemonic == "call":
            entries.add(target)
        for site, name in sites.items():
            if site < target < patched[site]:
                fatal.append((name, site, insn.address, insn.mnemonic, target))

    # A patch must not separate a comparison from the branch that reads its
    # result.  The flags are produced inside the trampoline and consumed after
    # the jump back, so anything the return path touches decides the branch.
    # `goldWrite` was exactly this: cmp [eax+0xc], ebx inside, je right after.
    FLAGGING = ("cmp", "test", "add", "sub", "and", "or", "xor", "inc", "dec",
                "shl", "shr", "neg")
    for site, end in patched.items():
        offset = site - start
        window = list(md.disasm(body[offset:offset + 48], site))
        inside = [i for i in window if i.address < end]
        after = next((i for i in window if i.address >= end), None)
        if not inside or after is None:
            continue
        if (inside[-1].mnemonic in FLAGGING
                and after.mnemonic.startswith("j")
                and after.mnemonic != "jmp"):
            fatal.append((sites[site], site, inside[-1].address,
                          f"{inside[-1].mnemonic} feeds", after.address))

    # Relocating a control transfer is where inline hooking is most fragile:
    # the trampoline has to rewrite the displacement and emit both paths.  A
    # site whose patch swallows one is not automatically broken, but it is the
    # first thing to move when a hook misbehaves for no visible reason.
    for site, end in patched.items():
        offset = site - start
        for insn in md.disasm(body[offset:offset + 32], site):
            if insn.address >= end:
                break
            if (insn.mnemonic.startswith("j") or insn.mnemonic in ("call", "ret")):
                risky.append((sites[site], site, insn.address, insn.mnemonic))
                break

    # An instruction that addresses memory through ESP has to be relocated into
    # the trampoline, where the stack pointer is Frida's business rather than the
    # game's.  Whether that is what broke them is not proven, but the two sites
    # in AddGold that made the game return with a destroyed callee-saved register
    # were both of this shape, and neither had any other feature in common.  Not
    # fatal on its own -- prefer a function entry when one is reachable.
    stacky = []
    for site, end in patched.items():
        offset = site - start
        for insn in md.disasm(body[offset:offset + 32], site):
            if insn.address >= end:
                break
            if site in entries:
                break
            if "esp" in insn.op_str and "[" in insn.op_str:
                stacky.append((sites[site], site, insn.address,
                               f"{insn.mnemonic} {insn.op_str}"))
                break

    # A scratch register loaded before the site and read after it has to survive
    # the trampoline.  The level write is why this check exists: `mov edx,[ebx+4]`
    # three bytes before it, `cmp [edx+0xc],0x10` twenty bytes after, and the game
    # died on every load from a save while a fresh character was fine.  Whether
    # the trampoline is what loses the register is not proven -- but three sites
    # have now failed with a value in flight across them and none without.
    #
    # Registers the hooked instruction itself uses are not counted: a hook whose
    # whole job is to rewrite EAX naturally has EAX live across it.
    carried = []
    scratch = {"eax", "ecx", "edx"}
    starts = sorted(entries)

    def names(regs):
        return {md.reg_name(reg) for reg in regs}

    # skipdata hands back a pseudo-instruction for every byte it could not
    # decode, and asking one of those which registers it touches raises. .text
    # is full of data in any build, so this is the difference between a report
    # and a traceback on an unfamiliar binary -- which is now a thing somebody
    # will point this at.
    def accessed(insn):
        return (set(), set()) if insn.id == 0 else insn.regs_access()

    for site, end in patched.items():
        if site in entries:
            continue                     # a function entry has a real frame
        index = bisect.bisect_right(starts, site) - 1
        if index < 0 or not 0 < site - starts[index] <= 8192:
            continue
        # Walk forward from the containing function so the instruction
        # boundaries before the site are real ones rather than a guess: x86
        # cannot be disassembled backwards.
        before = []
        for insn in md.disasm(body[starts[index] - start:], starts[index]):
            if insn.address >= site:
                break
            before.append(insn)
        touched = set()
        for insn in md.disasm(body[site - start:site - start + 32], site):
            if insn.address >= end:
                break
            read, written = accessed(insn)
            touched |= names(read) | names(written)
        loaded = set()
        for insn in before[-4:]:
            loaded |= names(accessed(insn)[1])
        used = set()
        for insn in md.disasm(body[end - start:end - start + 32], end):
            if insn.address >= end + 24:
                break
            used |= names(accessed(insn)[0])
        live = (loaded & used & scratch) - touched
        if live:
            carried.append((sites[site], site, sorted(live)))

    # Two hooks whose patched bytes overlap corrupt each other's trampoline.
    ordered = sorted(patched.items())
    for (site, end), (next_site, _) in zip(ordered, ordered[1:]):
        if next_site < end:
            fatal.append((f"{sites[site]}/{sites[next_site]}", site, site,
                          "overlaps", next_site))

    for name, site, source, mnemonic, target in fatal:
        span = patched[site] - site
        print(f"FATAL {name} @ 0x{site:08X} (+{span}b): {mnemonic} at "
              f"0x{source:08X} jumps to 0x{target:08X}, inside the trampoline")
    for name, site, source, mnemonic in risky:
        print(f"warn  {name} @ 0x{site:08X}: the patch relocates a "
              f"{mnemonic} at 0x{source:08X}")
    for name, site, source, text in stacky:
        print(f"warn  {name} @ 0x{site:08X}: the patch relocates an "
              f"ESP-relative `{text}` at 0x{source:08X}")
    for name, site, live in carried:
        print(f"warn  {name} @ 0x{site:08X}: {', '.join(live).upper()} is "
              f"loaded before the patch and read after it")
    print(f"{len(sites)} hook sites checked, {len(fatal)} unusable, "
          f"{len(risky)} relocating a branch, {len(stacky)} ESP-relative, "
          f"{len(carried)} carrying a register across")

    found = signatures(sites, start, body)
    if rewrite:
        write_signatures(found, exe)
    else:
        print(compare_signatures(found, exe))
    return 1 if fatal else 0


if __name__ == "__main__":
    raise SystemExit(main())
